#!/bin/bash
(sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.oleg.com"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.yandex.ru"
sleep 0.1
echo "www.google.com"
sleep 0.1
echo "www.nokia.com"
sleep 0.1
echo "www.fr.ru"
sleep 0.1
echo "www.love.ru"
sleep 0.1
echo "www.dfg.com"
sleep 0.1
echo "ewqewq"
sleep 0.1
echo "dsaddadaa"
sleep 0.1
echo "www.rts.ru"
sleep 0.1
echo "www.nginx.com"
sleep 0.1
echo "www.apple.com"
sleep 0.1
echo "dsadasdassa"
sleep 0.1
echo "wwewyanewewu"
sleep 0.1
echo "\n"
sleep 0.1
echo "www.oleg.com"
sleep 0.1
echo "www.asd.org"
sleep 0.1
echo "yandex.music.ru"
sleep 3) | nc 0 45678